### ISSUE TITLE
Building examples with`make` fails

### ISSUE THREAD

**Issue by eliminmax** [djytw/libnbt#3]
Running `make` within the example directory fails using GNU Make 4.3 and gcc 11.2.0 (Ubuntu 11.2.0-19ubuntu1), on Pop!_OS (Linux, like Ubuntu) fails, with the following error:
```
gcc basic.c ../nbt.c -o ../target/basic -Wall -g  -lz -L. -I..
gcc basic_opt.c ../nbt.c -o ../target/basic_opt -Wall -g  -lz -L. -I..
basic_opt.c: In function ‘main’:
basic_opt.c:60:35: error: ‘ERROR_BUFFER_OVERFLOW’ undeclared (first use in this function); did you mean ‘LIBNBT_ERROR_BUFFER_OVERFLOW’?
   60 |         if (ret && error.errid == ERROR_BUFFER_OVERFLOW) {
      |                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                   LIBNBT_ERROR_BUFFER_OVERFLOW
basic_opt.c:60:35: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:21: ../target/basic_opt] Error 1
```

Replacing `ERROR_BUFFER_OVERFLOW` with `LIBNBT_ERROR_BUFFER_OVERFLOW` as suggested appears to fix the error, but literally just cloned the repository, and I'm not a C programmer, so I'd rather not open a pull request without more of an understanding of what's going on.

**Comment by djytw** [comment]
Thanks. Now fixed in 085769a5ab2bb6cbd046f83833db64303b1a0dd5
